# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ASP.NET MVC CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, azure-vm]  # Replace with your Azure VM configuration

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set working directory
        uses: <path/to/directory>

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 4.5

      - name: Restore dependencies
        shell: cmd
        run: nuget restore

      - name: Build application
        shell: cmd
        run: dotnet build --configuration Release

      - name: Run tests
        shell: cmd
        run: dotnet test --configuration Release

      - name: Publish application
        shell: cmd
        run: dotnet publish --no-restore --configuration Release --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: application-artifact
          path: ./publish

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: application-artifact

      - name: Deploy to Azure VM
        uses: azure/ssh-action@v3
        with:
          host: <azure-vm-hostname>
          username: <azure-vm-username>
          password: <azure-vm-password>
          port: 5985
          script: |
            $path = "C:\inetpub\wwwroot\my-app"
            Remove-Item -Path $path\* -Recurse -Force
            Expand-Archive -Path $env:GITHUB_WORKSPACE\application-artifact.zip -DestinationPath $path -Force

